global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['localhost:9100']
